# yaml-language-server: $schema=../../../symfony/dependency-injection/Loader/schema/services.schema.json
services:
  _defaults:
    autowire: true
    autoconfigure: true

  Clickpress\ContaoUmamiBundle\:
    resource: ../src
    exclude: ../src/{ContaoManager,DependencyInjection,ContaoUmamiBundle.php}
